version: '3.8'
name: 'project-mod'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "9080:8080"

  service-discovery:
    container_name: service-discovery
    build:
      context: service-discovery
      dockerfile: Dockerfile
    ports:
      - "9081:8080"