spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - name: CircuitBreaker
          args:
            name: default
        - name: Retry
          args:
            retries: 3
            statuses:
              - REQUEST_TIMEOUT
              - SERVICE_UNAVAILABLE

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9080/realms/mod
        registration:
          keycloak:
            provider: keycloak
            client-id: oauth-client
            client-secret: A578ODWr8zhyk4JZV7Wy2WRYnGY6lN4t
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
              - role

# Service Discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}