spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - name: CircuitBreaker
          args:
            name: default
        - name: Retry
          args:
            retries: 3
            statuses:
              - REQUEST_TIMEOUT
              - SERVICE_UNAVAILABLE

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9080/realms/mod}
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: JVyf60akqH7xWruqu5vm9wknO55q0Vyc
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
              - role

# Service Discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: TRACE