spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: default
        - name: Retry
          args:
            retries: 3
            statuses:
              - REQUEST_TIMEOUT
              - SERVICE_UNAVAILABLE

# Service Discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}